// Generated by rstantools.  Do not edit by hand.

/*
    qordstan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    qordstan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with qordstan.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_model_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_model");
    reader.add_event(103, 101, "end", "model_model");
    return reader;
}
template <typename T0__, typename T1__>
typename boost::math::tools::promote_args<T0__, T1__>::type
Fa(const T0__& x,
       const T1__& p, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        current_statement_begin__ = 4;
        return stan::math::promote_scalar<fun_return_scalar_t__>((logical_lt(x, 0) ? (p * stan::math::exp((x * (1 - p)))) : (p + ((1 - p) * (1 - stan::math::exp((-(x) * p))))) ));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct Fa_functor__ {
    template <typename T0__, typename T1__>
        typename boost::math::tools::promote_args<T0__, T1__>::type
    operator()(const T0__& x,
       const T1__& p, std::ostream* pstream__) const {
        return Fa(x, p, pstream__);
    }
};
template <typename T0__, typename T1__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
Fa_vec(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& x,
           const T1__& p, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 9;
        validate_non_negative_index("probs", "num_elements(x)", num_elements(x));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> probs(num_elements(x));
        stan::math::initialize(probs, DUMMY_VAR__);
        stan::math::fill(probs, DUMMY_VAR__);
        current_statement_begin__ = 10;
        for (int i = 1; i <= num_elements(x); ++i) {
            current_statement_begin__ = 11;
            stan::model::assign(probs, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                        Fa(get_base1(x, i, "x", 1), p, pstream__), 
                        "assigning variable probs");
        }
        current_statement_begin__ = 13;
        return stan::math::promote_scalar<fun_return_scalar_t__>(probs);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct Fa_vec_functor__ {
    template <typename T0__, typename T1__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& x,
           const T1__& p, std::ostream* pstream__) const {
        return Fa_vec(x, p, pstream__);
    }
};
template <typename T0__>
int
to_int(const T0__& x,
           const int& min_val,
           const int& max_val, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__>::type local_scalar_t__;
    typedef int fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 18;
        int range(0);
        (void) range;  // dummy to suppress unused var warning
        stan::math::fill(range, std::numeric_limits<int>::min());
        stan::math::assign(range,divide(((max_val - min_val) + 1), 2));
        current_statement_begin__ = 19;
        int mid_pt(0);
        (void) mid_pt;  // dummy to suppress unused var warning
        stan::math::fill(mid_pt, std::numeric_limits<int>::min());
        stan::math::assign(mid_pt,(min_val + range));
        current_statement_begin__ = 20;
        int out(0);
        (void) out;  // dummy to suppress unused var warning
        stan::math::fill(out, std::numeric_limits<int>::min());
        current_statement_begin__ = 21;
        while (as_bool(logical_gt(range, 0))) {
            current_statement_begin__ = 22;
            if (as_bool(logical_eq(x, mid_pt))) {
                current_statement_begin__ = 23;
                stan::math::assign(out, mid_pt);
                current_statement_begin__ = 24;
                stan::math::assign(range, 0);
            } else {
                current_statement_begin__ = 26;
                stan::math::assign(range, divide((range + 1), 2));
                current_statement_begin__ = 27;
                stan::math::assign(mid_pt, (logical_gt(x, mid_pt) ? (mid_pt + range) : (mid_pt - range) ));
            }
        }
        current_statement_begin__ = 30;
        return stan::math::promote_scalar<fun_return_scalar_t__>(out);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct to_int_functor__ {
    template <typename T0__>
        int
    operator()(const T0__& x,
           const int& min_val,
           const int& max_val, std::ostream* pstream__) const {
        return to_int(x, min_val, max_val, pstream__);
    }
};
template <typename T0__, typename T1__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
lower_cut(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& x,
              const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& cuts,
              const int& J, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 35;
        validate_non_negative_index("val", "num_elements(x)", num_elements(x));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> val(num_elements(x));
        stan::math::initialize(val, DUMMY_VAR__);
        stan::math::fill(val, DUMMY_VAR__);
        current_statement_begin__ = 36;
        for (int i = 1; i <= num_elements(x); ++i) {
            current_statement_begin__ = 38;
            if (as_bool(logical_eq(get_base1(x, i, "x", 1), 1))) {
                current_statement_begin__ = 38;
                stan::model::assign(val, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            stan::math::negative_infinity(), 
                            "assigning variable val");
            } else if (as_bool(logical_eq(get_base1(x, i, "x", 1), 2))) {
                current_statement_begin__ = 40;
                stan::model::assign(val, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable val");
            } else {
                current_statement_begin__ = 41;
                stan::model::assign(val, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            get_base1(cuts, (to_int(get_base1(x, i, "x", 1), 0, (J + 1), pstream__) - 2), "cuts", 1), 
                            "assigning variable val");
            }
        }
        current_statement_begin__ = 43;
        return stan::math::promote_scalar<fun_return_scalar_t__>(val);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct lower_cut_functor__ {
    template <typename T0__, typename T1__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& x,
              const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& cuts,
              const int& J, std::ostream* pstream__) const {
        return lower_cut(x, cuts, J, pstream__);
    }
};
template <typename T0__, typename T1__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
upper_cut(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& x,
              const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& cuts,
              const int& J, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 48;
        validate_non_negative_index("val", "num_elements(x)", num_elements(x));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> val(num_elements(x));
        stan::math::initialize(val, DUMMY_VAR__);
        stan::math::fill(val, DUMMY_VAR__);
        current_statement_begin__ = 49;
        for (int i = 1; i <= num_elements(x); ++i) {
            current_statement_begin__ = 50;
            if (as_bool(logical_eq(get_base1(x, i, "x", 1), 1))) {
                current_statement_begin__ = 50;
                stan::model::assign(val, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable val");
            } else if (as_bool(logical_eq(get_base1(x, i, "x", 1), J))) {
                current_statement_begin__ = 51;
                stan::model::assign(val, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            stan::math::positive_infinity(), 
                            "assigning variable val");
            } else {
                current_statement_begin__ = 52;
                stan::model::assign(val, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            get_base1(cuts, (to_int(get_base1(x, i, "x", 1), 0, (J + 1), pstream__) - 1), "cuts", 1), 
                            "assigning variable val");
            }
        }
        current_statement_begin__ = 54;
        return stan::math::promote_scalar<fun_return_scalar_t__>(val);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct upper_cut_functor__ {
    template <typename T0__, typename T1__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__>::type, Eigen::Dynamic, 1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& x,
              const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& cuts,
              const int& J, std::ostream* pstream__) const {
        return upper_cut(x, cuts, J, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type, Eigen::Dynamic, 1>
logvero(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
            const Eigen::Matrix<T1__, Eigen::Dynamic, Eigen::Dynamic>& x,
            const Eigen::Matrix<T2__, Eigen::Dynamic, 1>& beta,
            const Eigen::Matrix<T3__, Eigen::Dynamic, 1>& delta,
            const T4__& p,
            const int& J, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 59;
        validate_non_negative_index("logv", "num_elements(y)", num_elements(y));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> logv(num_elements(y));
        stan::math::initialize(logv, DUMMY_VAR__);
        stan::math::fill(logv, DUMMY_VAR__);
        current_statement_begin__ = 60;
        validate_non_negative_index("cuts", "num_elements(delta)", num_elements(delta));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> cuts(num_elements(delta));
        stan::math::initialize(cuts, DUMMY_VAR__);
        stan::math::fill(cuts, DUMMY_VAR__);
        stan::math::assign(cuts,cumulative_sum(stan::math::exp(delta)));
        current_statement_begin__ = 61;
        validate_non_negative_index("pred", "num_elements(y)", num_elements(y));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> pred(num_elements(y));
        stan::math::initialize(pred, DUMMY_VAR__);
        stan::math::fill(pred, DUMMY_VAR__);
        stan::math::assign(pred,multiply(x, beta));
        current_statement_begin__ = 62;
        validate_non_negative_index("ucut", "num_elements(y)", num_elements(y));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> ucut(num_elements(y));
        stan::math::initialize(ucut, DUMMY_VAR__);
        stan::math::fill(ucut, DUMMY_VAR__);
        stan::math::assign(ucut,upper_cut(y, cuts, J, pstream__));
        current_statement_begin__ = 63;
        validate_non_negative_index("lcut", "num_elements(y)", num_elements(y));
        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lcut(num_elements(y));
        stan::math::initialize(lcut, DUMMY_VAR__);
        stan::math::fill(lcut, DUMMY_VAR__);
        stan::math::assign(lcut,lower_cut(y, cuts, J, pstream__));
        current_statement_begin__ = 64;
        stan::math::assign(logv, stan::math::log(subtract(Fa_vec(subtract(ucut, pred), p, pstream__), Fa_vec(subtract(lcut, pred), p, pstream__))));
        current_statement_begin__ = 65;
        return stan::math::promote_scalar<fun_return_scalar_t__>(logv);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct logvero_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type, Eigen::Dynamic, 1>
    operator()(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& y,
            const Eigen::Matrix<T1__, Eigen::Dynamic, Eigen::Dynamic>& x,
            const Eigen::Matrix<T2__, Eigen::Dynamic, 1>& beta,
            const Eigen::Matrix<T3__, Eigen::Dynamic, 1>& delta,
            const T4__& p,
            const int& J, std::ostream* pstream__) const {
        return logvero(y, x, beta, delta, p, J, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_model
  : public stan::model::model_base_crtp<model_model> {
private:
        int J;
        int n;
        int k;
        double p;
        vector_d y;
        matrix_d x;
        double sigma_beta;
        double sigma_delta;
public:
    model_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_model_namespace::model_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 72;
            context__.validate_dims("data initialization", "J", "int", context__.to_vec());
            J = int(0);
            vals_i__ = context__.vals_i("J");
            pos__ = 0;
            J = vals_i__[pos__++];
            current_statement_begin__ = 73;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            current_statement_begin__ = 74;
            context__.validate_dims("data initialization", "k", "int", context__.to_vec());
            k = int(0);
            vals_i__ = context__.vals_i("k");
            pos__ = 0;
            k = vals_i__[pos__++];
            current_statement_begin__ = 75;
            context__.validate_dims("data initialization", "p", "double", context__.to_vec());
            p = double(0);
            vals_r__ = context__.vals_r("p");
            pos__ = 0;
            p = vals_r__[pos__++];
            check_greater_or_equal(function__, "p", p, 0);
            check_less_or_equal(function__, "p", p, 1);
            current_statement_begin__ = 76;
            validate_non_negative_index("y", "n", n);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(n));
            y = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                y(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "y", y, 1);
            check_less_or_equal(function__, "y", y, J);
            current_statement_begin__ = 77;
            validate_non_negative_index("x", "n", n);
            validate_non_negative_index("x", "k", k);
            context__.validate_dims("data initialization", "x", "matrix_d", context__.to_vec(n,k));
            x = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n, k);
            vals_r__ = context__.vals_r("x");
            pos__ = 0;
            size_t x_j_2_max__ = k;
            size_t x_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < x_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_j_1_max__; ++j_1__) {
                    x(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 78;
            context__.validate_dims("data initialization", "sigma_beta", "double", context__.to_vec());
            sigma_beta = double(0);
            vals_r__ = context__.vals_r("sigma_beta");
            pos__ = 0;
            sigma_beta = vals_r__[pos__++];
            current_statement_begin__ = 79;
            context__.validate_dims("data initialization", "sigma_delta", "double", context__.to_vec());
            sigma_delta = double(0);
            vals_r__ = context__.vals_r("sigma_delta");
            pos__ = 0;
            sigma_delta = vals_r__[pos__++];
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 84;
            validate_non_negative_index("betas", "k", k);
            num_params_r__ += k;
            current_statement_begin__ = 85;
            validate_non_negative_index("deltas", "(J - 2)", (J - 2));
            num_params_r__ += (J - 2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_model() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 84;
        if (!(context__.contains_r("betas")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable betas missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("betas");
        pos__ = 0U;
        validate_non_negative_index("betas", "k", k);
        context__.validate_dims("parameter initialization", "betas", "vector_d", context__.to_vec(k));
        Eigen::Matrix<double, Eigen::Dynamic, 1> betas(k);
        size_t betas_j_1_max__ = k;
        for (size_t j_1__ = 0; j_1__ < betas_j_1_max__; ++j_1__) {
            betas(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(betas);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable betas: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 85;
        if (!(context__.contains_r("deltas")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable deltas missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("deltas");
        pos__ = 0U;
        validate_non_negative_index("deltas", "(J - 2)", (J - 2));
        context__.validate_dims("parameter initialization", "deltas", "vector_d", context__.to_vec((J - 2)));
        Eigen::Matrix<double, Eigen::Dynamic, 1> deltas((J - 2));
        size_t deltas_j_1_max__ = (J - 2);
        for (size_t j_1__ = 0; j_1__ < deltas_j_1_max__; ++j_1__) {
            deltas(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(deltas);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable deltas: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 84;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> betas;
            (void) betas;  // dummy to suppress unused var warning
            if (jacobian__)
                betas = in__.vector_constrain(k, lp__);
            else
                betas = in__.vector_constrain(k);
            current_statement_begin__ = 85;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> deltas;
            (void) deltas;  // dummy to suppress unused var warning
            if (jacobian__)
                deltas = in__.vector_constrain((J - 2), lp__);
            else
                deltas = in__.vector_constrain((J - 2));
            // transformed parameters
            current_statement_begin__ = 89;
            validate_non_negative_index("gammas", "(J - 2)", (J - 2));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> gammas((J - 2));
            stan::math::initialize(gammas, DUMMY_VAR__);
            stan::math::fill(gammas, DUMMY_VAR__);
            stan::math::assign(gammas,cumulative_sum(stan::math::exp(deltas)));
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 89;
            size_t gammas_j_1_max__ = (J - 2);
            for (size_t j_1__ = 0; j_1__ < gammas_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(gammas(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: gammas" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable gammas: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            {
            current_statement_begin__ = 94;
            validate_non_negative_index("logv_obs", "num_elements(y)", num_elements(y));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> logv_obs(num_elements(y));
            stan::math::initialize(logv_obs, DUMMY_VAR__);
            stan::math::fill(logv_obs, DUMMY_VAR__);
            current_statement_begin__ = 95;
            stan::math::assign(logv_obs, logvero(y, x, betas, deltas, p, J, pstream__));
            current_statement_begin__ = 96;
            lp_accum__.add(sum(logv_obs));
            current_statement_begin__ = 98;
            lp_accum__.add(normal_log<propto__>(betas, 0, sigma_beta));
            current_statement_begin__ = 99;
            lp_accum__.add(normal_log<propto__>(deltas, 0, sigma_delta));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("betas");
        names__.push_back("deltas");
        names__.push_back("gammas");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(k);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((J - 2));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((J - 2));
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> betas = in__.vector_constrain(k);
        size_t betas_j_1_max__ = k;
        for (size_t j_1__ = 0; j_1__ < betas_j_1_max__; ++j_1__) {
            vars__.push_back(betas(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> deltas = in__.vector_constrain((J - 2));
        size_t deltas_j_1_max__ = (J - 2);
        for (size_t j_1__ = 0; j_1__ < deltas_j_1_max__; ++j_1__) {
            vars__.push_back(deltas(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 89;
            validate_non_negative_index("gammas", "(J - 2)", (J - 2));
            Eigen::Matrix<double, Eigen::Dynamic, 1> gammas((J - 2));
            stan::math::initialize(gammas, DUMMY_VAR__);
            stan::math::fill(gammas, DUMMY_VAR__);
            stan::math::assign(gammas,cumulative_sum(stan::math::exp(deltas)));
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t gammas_j_1_max__ = (J - 2);
                for (size_t j_1__ = 0; j_1__ < gammas_j_1_max__; ++j_1__) {
                    vars__.push_back(gammas(j_1__));
                }
            }
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_model";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t betas_j_1_max__ = k;
        for (size_t j_1__ = 0; j_1__ < betas_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "betas" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t deltas_j_1_max__ = (J - 2);
        for (size_t j_1__ = 0; j_1__ < deltas_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "deltas" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t gammas_j_1_max__ = (J - 2);
            for (size_t j_1__ = 0; j_1__ < gammas_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "gammas" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t betas_j_1_max__ = k;
        for (size_t j_1__ = 0; j_1__ < betas_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "betas" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t deltas_j_1_max__ = (J - 2);
        for (size_t j_1__ = 0; j_1__ < deltas_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "deltas" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t gammas_j_1_max__ = (J - 2);
            for (size_t j_1__ = 0; j_1__ < gammas_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "gammas" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_model_namespace::model_model stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
